CREATE TABLE HACKOVERFLOW.ABHISHEK.MEDIUM_HASHMAP_TAG_TREND(tags varchar, stories varchar, writers varchar);
--LOAD DATA FROM WEBUI
CREATE TABLE GOOGLE_TREND_RELATIVE_TOP_5(date varchar, technology varchar, trend varchar);
--LOAD DATA FROM WEBUI
CREATE TABLE GOOGLE_TRENDS_INDIVIDUAL(date varchar, technology varchar, trend varchar);
--LOAD DATA FROM WEBUI
create table extracted_data_from_image(parent_type varchar, subcategory varchar, tool_tech varchar);
--LOAD FROM WEB_UI
create table lookup_table(tools_tech varchar);
INSERT INTO DARSHITH.lookup_table SELECT DISTINCT upper(TECHNOLOGY) FROM HACKOVERFLOW.ISHWAR.GOOGLE_TREND_RELATIVE_TOP_5 ;

--LIST OF TABLES;

--DARSHITH
SELECT * FROM HACKOVERFLOW.DARSHITH.LOOKUP_TABLE ORDER BY 1;
SELECT * FROM DARSHITH.EXTRACTED_DATA_FROM_IMAGE;


--ABHISHEK
SELECT * FROM HACKOVERFLOW.ABHISHEK.MEDIUM_HASHMAP_TAG_TREND LIMIT 5;

--ISHWAR
SELECT * FROM HACKOVERFLOW.ISHWAR.GOOGLE_TREND_RELATIVE_TOP_5 LIMIT 5;
SELECT * FROM HACKOVERFLOW.ISHWAR.GOOGLE_TRENDS_INDIVIDUAL LIMIT 5;


--SRIKANT
SELECT * FROM HACKOVERFLOW.SRIKANT.HASHMAP_SKILLS_REPO_SKILLS LIMIT 5;
